app:
  name: "go-groc-store"
  description: "online grocery store"
  version: "1.0"
  environment: "dit"

http:
  port: 8080
log:
  level: "debug"

db:
  db_name: "go-groc-store-dit.db"
  db_path: "./"
  db_url : "./go-groc-store-dit.db"