app:
  name: "go-groc-store"
  description: "online grocery store"
  version: "1.0"
  environment: "dit"

http:
  port: 8080
log:
  level: "debug"

db:
  dbname: "go-groc-store-dit.db"
  dbpath: "./"
  dburl : "./go-groc-store-dit.db"